CUDA_VISIBLE_DEVICES=0,1 \
python train_reader.py \
--do_train \
--prefix \
hotpot_reader_deberta_large \
--model_name \
deepset/deberta-v3-large-squad2 \
--tokenizer_path \
deepset/deberta-v3-large-squad2 \
--dataset_type \
hotpot \
--train_file \
datasets/mrc/hotpotqa/hotpot_train_v1.1.json \
--predict_file \
datasets/mrc/hotpotqa/hotpot_dev_distractor_v1.json \
--train_batch_size \
8 \
--learning_rate \
1e-5 \
--fp16 \
--max_seq_len \
1024 \
--num_train_epochs \
16 \
--predict_batch_size \
32 \
--warmup-ratio \
0.1 \
--log_period_ratio \
0.01 \
--eval_period_ratio \
0.3
